#项目启动窗口
server:
  port: 8080
#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/famliy_service_plantform?serverTimeZone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#配置mybatis
mybatis:
  mapper-locations: classpath:com/yeyangshu/mapper/*.xml

logging:
  level:
    com:
      yeyangshu:
        mapper: debug


